version: '3'
services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:v4-update-lp-alpine
    container_name: lavalink
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    networks:
      - discordbot
    expose:
      - 2333
    ports:
      - 2333:2333

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: stack.env
    networks:
      - discordbot
    ports:
      - 4000:4000
    depends_on:
      lavalink:
        condition: service_started

networks:
  discordbot:
    name: discordbot
