version: '3'
services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:v4-update-lp-alpine
    container_name: lavalink
    restart: unless-stopped
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - discordbot
    expose:
      - 2333
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep -q 2333"]

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env.prod
        required: false
      - path: stack.env
        required: false
    networks:
      - discordbot
    depends_on:
      lavalink:
        condition: service_healthy

networks:
  discordbot:
    name: discordbot