version: '3'
services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:v4-update-lp-alpine
    container_name: lavalink
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - LAVALINK_PLUGINS_0_DEPENDENCY=me.rohank05:lavalink-filter-plugin:0.0.4
      - LAVALINK_PLUGINS_0_REPOSITORY=https://jitpack.io
      - LAVALINK_PLUGINS_DIR=/opt/Lavalink/plugins/
      - METRICS_PROMETHEUS_ENABLED=true
      - METRICS_PROMETHEUS_ENDPOINT=/metrics
      - LAVALINK_SERVER_SOURCES_YOUTUBE=true
      - LAVALINK_SERVER_SOURCES_BANDCAMP=true
      - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=true
      - LAVALINK_SERVER_SOURCES_TWITCH=true
      - LAVALINK_SERVER_SOURCES_VIMEO=true
      - LAVALINK_SERVER_SOURCES_HTTP=true
      - LAVALINK_SERVER_SOURCES_LOCAL=false
      - LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL=noreplydragonaere@gmail.com
      - LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD=#Dragonaere@2.4ghz
    networks:
      - discordbot
    expose:
      - 2333
    ports:
      - 2333:2333
    healthcheck:
      test: ["CMD-SHELL", "wget --header='Authorization: youshallnotpass' http://localhost:2333/v4/info"]
      retries: 1

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: stack.env
    networks:
      - discordbot
    depends_on:
      lavalink:
        condition: service_healthy
        required: false

networks:
  discordbot:
    name: discordbot