version: '3'
services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:v4-update-lp-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - discordbot
    expose:
      - 2333
    healthcheck:
      test: ["CMD-SHELL", "wget --header='Authorization: youshallnotpass' http://localhost:2333/v4/info"]
      retries: 1

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: stack.env
    networks:
      - discordbot
    depends_on:
      lavalink:
        condition: service_healthy
        required: false

networks:
  discordbot:
    name: discordbot