name: Deploy Lavalink
on:
  push:
    paths:
      - 'Lavalink.jar'
      - 'application.yml'
jobs:
  deploy-lavalink:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PM2
        run: |
          npm install pm2 -g

      - name: Start Lavalink with PM2
        run: |
          pm2 start Lavalink.jar --name lavalink --interpreter none