name: Deploy Lavalink
on:
  push:
    paths:
      - 'Lavalink.jar'
      - 'application.yml'
jobs:
  deploy-lavalink:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install PM2
        run: |
          pnpm add -g pm2

      - name: Start Lavalink with PM2
        run: |
          pm2 start Lavalink.jar --name lavalink --interpreter none